name: Test

on:
  pull_request:
    branches:
      - development
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    environment:
      name: development

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tests
        run: tox
